/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }

    fun getJin(): String {
        return "화이팅 진~~~"
    }
}
